import { buildGrade, type LessonBrief } from './_authoring.js';

/**
 * Kelas 6 — Fase C. Bilangan cacah besar & bilangan bulat pada garis, operasi
 * pecahan & desimal, empat operasi campuran, bangun ruang (kubus, balok) dan
 * visualisasi spasial, penyajian & analisis data. Difficulty ADVANCED.
 */
const BRIEFS: LessonBrief[] = [
  {
    id: 'sd-mtk-k6-01',
    archetype: 'place-value',
    element: 'bilangan',
    unitTitle: 'Bilangan Cacah Besar',
    title: 'Nilai Tempat dan Bentuk Panjang sampai Jutaan',
    summary: 'Menguraikan nilai tempat bilangan cacah besar dan menuliskannya dalam bentuk panjang.',
    learningObjective: 'Siswa dapat menentukan nilai tempat dan menguraikan bilangan cacah sampai 1.000.000.',
    params: { numbers: [472039, 805604, 960018, 234875, 719260, 500903], askPlaces: [5, 3, 4, 1] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-02',
    archetype: 'number-line',
    element: 'bilangan',
    unitTitle: 'Bilangan Bulat pada Garis',
    title: 'Bilangan Bulat Positif dan Negatif',
    summary: 'Menjumlah dan mengurang bilangan bulat sebagai lompatan pada garis bilangan.',
    learningObjective: 'Siswa dapat menyelesaikan operasi bilangan bulat pada garis bilangan.',
    params: { min: -20, max: 20, step: 1, allowNegative: true, jumps: [[5, -12], [-8, 15], [3, -14], [-6, 9], [12, -18]] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-03',
    archetype: 'fractions',
    element: 'bilangan',
    unitTitle: 'Operasi Pecahan dan Desimal',
    title: 'Membandingkan dan Mengoperasikan Pecahan',
    summary: 'Membandingkan pecahan berpenyebut beda dan mengaitkannya dengan desimal.',
    learningObjective: 'Siswa dapat membandingkan pecahan, menyederhanakan, dan menghubungkannya dengan desimal.',
    params: {
      denominators: [2, 3, 4, 5, 6, 10],
      includeDecimal: true,
      compares: [
        [3, 5, 5, 8],
        [7, 10, 3, 4],
        [5, 6, 9, 10],
        [2, 3, 5, 8],
        [3, 4, 7, 12],
        [4, 5, 5, 6],
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-04',
    archetype: 'operations',
    element: 'bilangan',
    unitTitle: 'Operasi Hitung Campuran',
    title: 'Perkalian dan Pembagian dalam Operasi Campuran',
    summary: 'Menyelesaikan operasi hitung campuran yang memuat perkalian dan pembagian.',
    learningObjective: 'Siswa dapat menyelesaikan operasi hitung campuran bilangan cacah.',
    params: { operation: 'MIX', factPairs: [[48, 12], [63, 9], [56, 7], [72, 8], [45, 15], [84, 6]] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-05',
    archetype: 'patterns',
    element: 'aljabar',
    unitTitle: 'Kalimat Matematika Empat Operasi',
    title: 'Menemukan Nilai yang Belum Diketahui',
    summary: 'Mengisi nilai belum diketahui pada kalimat empat operasi bilangan cacah sampai 1.000.',
    learningObjective: 'Siswa dapat menyelesaikan kalimat matematika empat operasi dengan satu nilai belum diketahui.',
    params: { sequences: [{ start: 12, diff: 12 }, { start: 50, diff: 25 }, { start: 200, diff: -15 }, { start: 9, diff: 13 }, { start: 480, diff: -40 }] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-06',
    archetype: 'number-line',
    element: 'aljabar',
    unitTitle: 'Menyeimbangkan Empat Operasi',
    title: 'Keseimbangan pada Operasi Campuran',
    summary: 'Menentukan bilangan agar kedua sisi kalimat operasi campuran bernilai sama.',
    learningObjective: 'Siswa dapat menyeimbangkan kalimat matematika operasi campuran sampai 1.000.',
    params: { min: 0, max: 1000, step: 25, jumps: [[300, 225], [550, -175], [700, 250], [900, -325], [450, 375]] },
  },
  {
    id: 'sd-mtk-k6-07',
    archetype: 'measurement',
    element: 'pengukuran',
    unitTitle: 'Keliling dan Luas Bangun Datar',
    title: 'Konversi Satuan dan Keliling Gabungan',
    summary: 'Mengonversi satuan panjang dan menghitung keliling bangun datar gabungan.',
    learningObjective: 'Siswa dapat menentukan keliling dan luas berbagai bangun datar serta gabungannya.',
    params: {
      quantity: 'panjang',
      base: 'm',
      sub: 'cm',
      factor: 100,
      objects: [
        { name: 'pagar taman', sub: 1250 },
        { name: 'lintasan lari', sub: 4000 },
        { name: 'bingkai foto', sub: 320 },
        { name: 'karpet', sub: 560 },
        { name: 'meja panjang', sub: 240 },
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-08',
    archetype: 'geometry',
    element: 'geometri',
    unitTitle: 'Bangun Ruang',
    title: 'Kubus, Balok, dan Visualisasi Spasial',
    summary: 'Mengonstruksi dan mengurai kubus dan balok serta mengenali bagian depan, atas, dan samping.',
    learningObjective: 'Siswa dapat mengonstruksi dan mengurai bangun ruang serta mengenali visualisasi spasialnya.',
    params: {
      shapes: [
        { name: 'kubus', sides: 12, vertices: 8 },
        { name: 'balok', sides: 12, vertices: 8 },
        { name: 'prisma segitiga', sides: 9, vertices: 6 },
        { name: 'limas segiempat', sides: 8, vertices: 5 },
      ],
      rects: [
        [10, 10],
        [14, 8],
        [12, 5],
        [9, 7],
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-09',
    archetype: 'data-chart',
    element: 'data',
    unitTitle: 'Analisis Data',
    title: 'Menafsirkan Diagram Batang dan Tabel Frekuensi',
    summary: 'Menyajikan dan menganalisis data banyak benda dan data hasil pengukuran.',
    learningObjective: 'Siswa dapat menyajikan dan menganalisis data untuk menarik kesimpulan.',
    params: {
      categories: [
        { name: 'Januari', count: 45 },
        { name: 'Februari', count: 52 },
        { name: 'Maret', count: 38 },
        { name: 'April', count: 60 },
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k6-10',
    archetype: 'money',
    element: 'pengukuran',
    unitTitle: 'Aritmetika Sosial',
    title: 'Belanja, Total, dan Kembalian',
    summary: 'Menghitung total belanja dan kembalian pada transaksi dengan beberapa barang.',
    learningObjective: 'Siswa dapat menyelesaikan masalah aritmetika sosial sederhana tentang belanja.',
    params: {
      paidWith: 100000,
      prices: [
        { item: 'sepatu', price: 65000 },
        { item: 'kaus kaki', price: 12000 },
        { item: 'topi', price: 25000 },
        { item: 'botol minum', price: 18000 },
      ],
    },
  },
];

export const { lessons: KELAS_6_LESSONS, videos: KELAS_6_VIDEOS } = buildGrade(6, BRIEFS);
