import { buildGrade, type LessonBrief } from './_authoring.js';

/** Kelas 2 — Fase A. Bilangan cacah sampai 100, pola, pengukuran tidak baku, bangun datar, piktogram. Picture-first (O8). */
const BRIEFS: LessonBrief[] = [
  {
    id: 'sd-mtk-k2-01',
    archetype: 'place-value',
    element: 'bilangan',
    unitTitle: 'Bilangan sampai 100',
    title: 'Puluhan dan Satuan sampai 100',
    summary: 'Menentukan nilai tempat puluhan dan satuan pada bilangan sampai 100.',
    learningObjective: 'Siswa dapat menentukan nilai tempat dan mengurai bilangan sampai 100.',
    params: { numbers: [24, 57, 30, 68, 91, 46], askPlaces: [1, 0] },
  },
  {
    id: 'sd-mtk-k2-02',
    archetype: 'number-line',
    element: 'bilangan',
    unitTitle: 'Penjumlahan pada Garis Bilangan',
    title: 'Penjumlahan sampai 100',
    summary: 'Menjumlah bilangan sampai 100 dengan melompat pada garis bilangan.',
    learningObjective: 'Siswa dapat menyelesaikan penjumlahan sampai 100 pada garis bilangan.',
    params: { min: 0, max: 100, step: 5, jumps: [[20, 15], [45, 30], [60, 25], [10, 40], [75, 20]] },
  },
  {
    id: 'sd-mtk-k2-03',
    archetype: 'number-line',
    element: 'bilangan',
    unitTitle: 'Pengurangan pada Garis Bilangan',
    title: 'Pengurangan sampai 100',
    summary: 'Mengurang bilangan sampai 100 dengan melompat mundur pada garis bilangan.',
    learningObjective: 'Siswa dapat menyelesaikan pengurangan sampai 100 pada garis bilangan.',
    params: { min: 0, max: 100, step: 5, jumps: [[80, -25], [65, -30], [90, -45], [50, -15], [100, -60]] },
  },
  {
    id: 'sd-mtk-k2-04',
    archetype: 'operations',
    element: 'bilangan',
    unitTitle: 'Perkalian Dasar',
    title: 'Perkalian sebagai Penjumlahan Berulang',
    summary: 'Memaknai perkalian bilangan kecil sebagai penjumlahan berulang.',
    learningObjective: 'Siswa dapat menyelesaikan perkalian bilangan satu angka.',
    params: { operation: 'MUL', factPairs: [[2, 3], [3, 3], [2, 5], [4, 2], [5, 2], [3, 4]] },
  },
  {
    id: 'sd-mtk-k2-05',
    archetype: 'patterns',
    element: 'aljabar',
    unitTitle: 'Pola Bilangan',
    title: 'Pola Loncat Dua dan Tiga',
    summary: 'Menemukan aturan pola bilangan yang meloncat dua dan tiga.',
    learningObjective: 'Siswa dapat melanjutkan pola bilangan dengan selisih tetap sampai 100.',
    params: { sequences: [{ start: 2, diff: 2 }, { start: 3, diff: 3 }, { start: 20, diff: -2 }, { start: 5, diff: 5 }, { start: 1, diff: 4 }] },
  },
  {
    id: 'sd-mtk-k2-06',
    archetype: 'number-line',
    element: 'aljabar',
    unitTitle: 'Kalimat Matematika',
    title: 'Mengisi Bilangan yang Hilang',
    summary: 'Mengisi bilangan yang belum diketahui pada kalimat penjumlahan dan pengurangan sampai 20.',
    learningObjective: 'Siswa dapat mengisi bilangan pada kalimat matematika bertanda "=" sampai 20.',
    params: { min: 0, max: 20, step: 1, jumps: [[7, 6], [12, 5], [9, 8], [4, 9], [15, 4]] },
  },
  {
    id: 'sd-mtk-k2-07',
    archetype: 'measurement',
    element: 'pengukuran',
    unitTitle: 'Berat Benda',
    title: 'Membandingkan Berat Benda',
    summary: 'Membandingkan berat benda dengan satuan tidak baku.',
    learningObjective: 'Siswa dapat membandingkan berat dua benda secara langsung dan dengan satuan tidak baku.',
    params: {
      quantity: 'berat',
      base: 'kantong',
      sub: 'kelereng',
      factor: 10,
      objects: [
        { name: 'apel', sub: 8 },
        { name: 'buku', sub: 20 },
        { name: 'pensil', sub: 3 },
        { name: 'botol', sub: 25 },
        { name: 'tas', sub: 40 },
      ],
    },
  },
  {
    id: 'sd-mtk-k2-08',
    archetype: 'money',
    element: 'pengukuran',
    unitTitle: 'Mengenal Uang',
    title: 'Nilai Uang Rupiah',
    summary: 'Mengenal pecahan uang rupiah dan membandingkan nilainya.',
    learningObjective: 'Siswa dapat mengenal dan membandingkan nilai pecahan uang rupiah.',
    params: {
      paidWith: 5000,
      prices: [
        { item: 'permen', price: 500 },
        { item: 'roti', price: 3000 },
        { item: 'susu', price: 4000 },
        { item: 'biskuit', price: 2000 },
      ],
    },
  },
  {
    id: 'sd-mtk-k2-09',
    archetype: 'geometry',
    element: 'geometri',
    unitTitle: 'Ciri Bangun Datar',
    title: 'Menghitung Sisi dan Sudut',
    summary: 'Menghitung banyak sisi dan titik sudut bangun datar.',
    learningObjective: 'Siswa dapat menyebutkan ciri bangun datar dari jumlah sisi dan titik sudutnya.',
    params: {
      shapes: [
        { name: 'segitiga', sides: 3, vertices: 3 },
        { name: 'persegi', sides: 4, vertices: 4 },
        { name: 'segi lima', sides: 5, vertices: 5 },
        { name: 'segi enam', sides: 6, vertices: 6 },
      ],
    },
  },
  {
    id: 'sd-mtk-k2-10',
    archetype: 'data-chart',
    element: 'data',
    unitTitle: 'Turus dan Piktogram',
    title: 'Menyortir dan Menyajikan Data',
    summary: 'Mengelompokkan data dan menyajikannya dengan turus dan piktogram sampai 4 kategori.',
    learningObjective: 'Siswa dapat menyortir dan menyajikan data dengan turus dan piktogram.',
    params: {
      categories: [
        { name: 'Merah', count: 7 },
        { name: 'Biru', count: 5 },
        { name: 'Hijau', count: 3 },
        { name: 'Kuning', count: 6 },
      ],
    },
  },
];

export const { lessons: KELAS_2_LESSONS, videos: KELAS_2_VIDEOS } = buildGrade(2, BRIEFS);
