import { buildGrade, type LessonBrief } from './_authoring.js';

/**
 * Kelas 5 — Fase C. Bilangan cacah sampai 1.000.000, pecahan & desimal,
 * perkalian/pembagian sampai 1.000, keliling & luas gabungan bangun datar,
 * penyajian data (piktogram, diagram batang, tabel frekuensi). Difficulty naik:
 * `fractions`/`operations`/`data-chart` diperkenalkan pada tingkat lebih tinggi (T068).
 */
const BRIEFS: LessonBrief[] = [
  {
    id: 'sd-mtk-k5-01',
    archetype: 'place-value',
    element: 'bilangan',
    unitTitle: 'Bilangan Cacah sampai 1.000.000',
    title: 'Nilai Tempat sampai Ratusan Ribu',
    summary: 'Membaca, menulis, dan menguraikan nilai tempat bilangan cacah sampai 1.000.000.',
    learningObjective: 'Siswa dapat menentukan nilai tempat serta menyusun dan mengurai bilangan sampai 1.000.000.',
    params: { numbers: [348256, 570431, 900070, 125684, 764019, 483200], askPlaces: [5, 4, 3, 2] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-02',
    archetype: 'operations',
    element: 'bilangan',
    unitTitle: 'Perkalian dan Pembagian sampai 1.000',
    title: 'Perkalian dan Pembagian Bilangan Besar',
    summary: 'Menyelesaikan perkalian dan pembagian bilangan cacah sampai 1.000.',
    learningObjective: 'Siswa dapat menyelesaikan perkalian dan pembagian bilangan cacah sampai 1.000.',
    params: { operation: 'MIX', factPairs: [[25, 8], [36, 6], [48, 4], [15, 12], [42, 7], [30, 9]] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-03',
    archetype: 'fractions',
    element: 'bilangan',
    unitTitle: 'Pecahan dan Desimal',
    title: 'Membandingkan Pecahan dan Menyederhanakan',
    summary: 'Membandingkan pecahan berpenyebut berbeda dan menyederhanakannya.',
    learningObjective: 'Siswa dapat membandingkan, menyederhanakan, dan mencari pecahan senilai.',
    params: {
      denominators: [2, 3, 4, 6, 8, 12],
      includeDecimal: true,
      compares: [
        [2, 3, 3, 4],
        [5, 6, 7, 8],
        [3, 4, 6, 8],
        [1, 2, 4, 8],
        [2, 5, 3, 7],
        [4, 6, 2, 3],
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-04',
    archetype: 'number-line',
    element: 'bilangan',
    unitTitle: 'Bilangan pada Garis',
    title: 'Menempatkan Bilangan Besar pada Garis',
    summary: 'Menempatkan dan mengurutkan bilangan cacah besar pada garis bilangan.',
    learningObjective: 'Siswa dapat mengurutkan dan menempatkan bilangan sampai 1.000.000 pada garis.',
    params: { min: 0, max: 100000, step: 5000, jumps: [[20000, 15000], [45000, 30000], [80000, -25000], [65000, -40000], [10000, 45000]] },
  },
  {
    id: 'sd-mtk-k5-05',
    archetype: 'patterns',
    element: 'aljabar',
    unitTitle: 'Kalimat Matematika Empat Operasi',
    title: 'Nilai Belum Diketahui pada Empat Operasi',
    summary: 'Mengisi nilai yang belum diketahui pada kalimat empat operasi bilangan cacah sampai 1.000.',
    learningObjective: 'Siswa dapat mengisi nilai belum diketahui pada kalimat penjumlahan, pengurangan, perkalian, dan pembagian sampai 1.000.',
    params: { sequences: [{ start: 8, diff: 8 }, { start: 25, diff: 25 }, { start: 100, diff: -12 }, { start: 7, diff: 11 }, { start: 250, diff: -30 }] },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-06',
    archetype: 'number-line',
    element: 'aljabar',
    unitTitle: 'Menyeimbangkan Operasi',
    title: 'Menjaga Keseimbangan Empat Operasi',
    summary: 'Menentukan bilangan agar kedua sisi kalimat empat operasi bernilai sama sampai 1.000.',
    learningObjective: 'Siswa dapat menyeimbangkan kalimat matematika empat operasi sampai 1.000.',
    params: { min: 0, max: 1000, step: 20, jumps: [[240, 180], [500, -140], [620, 200], [800, -260], [400, 340]] },
  },
  {
    id: 'sd-mtk-k5-07',
    archetype: 'measurement',
    element: 'pengukuran',
    unitTitle: 'Keliling dan Luas',
    title: 'Satuan Panjang dan Konversi',
    summary: 'Mengonversi antar-satuan panjang dan menerapkannya pada keliling.',
    learningObjective: 'Siswa dapat mengonversi antar-satuan panjang dan menghitung keliling bangun datar.',
    params: {
      quantity: 'panjang',
      base: 'm',
      sub: 'cm',
      factor: 100,
      objects: [
        { name: 'tali jemuran', sub: 450 },
        { name: 'pita', sub: 180 },
        { name: 'kabel', sub: 720 },
        { name: 'selang', sub: 900 },
        { name: 'kawat', sub: 265 },
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-08',
    archetype: 'geometry',
    element: 'geometri',
    unitTitle: 'Keliling dan Luas Gabungan',
    title: 'Keliling dan Luas Bangun Datar Gabungan',
    summary: 'Menentukan keliling dan luas segitiga, segiempat, dan gabungannya.',
    learningObjective: 'Siswa dapat menentukan keliling dan luas bangun datar serta gabungannya.',
    params: {
      shapes: [
        { name: 'persegi', sides: 4, vertices: 4 },
        { name: 'persegi panjang', sides: 4, vertices: 4 },
        { name: 'segitiga', sides: 3, vertices: 3 },
        { name: 'trapesium', sides: 4, vertices: 4 },
      ],
      rects: [
        [12, 7],
        [15, 8],
        [9, 9],
        [20, 6],
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-09',
    archetype: 'data-chart',
    element: 'data',
    unitTitle: 'Tabel Frekuensi',
    title: 'Menganalisis Data dengan Diagram Batang',
    summary: 'Menyajikan dan menganalisis data hasil pengukuran dalam diagram batang dan tabel frekuensi.',
    learningObjective: 'Siswa dapat mengurutkan, menyajikan, dan menganalisis data untuk mendapatkan informasi.',
    params: {
      categories: [
        { name: 'Kelas A', count: 28 },
        { name: 'Kelas B', count: 34 },
        { name: 'Kelas C', count: 21 },
        { name: 'Kelas D', count: 30 },
      ],
    },
    difficultyLevel: 'ADVANCED',
  },
  {
    id: 'sd-mtk-k5-10',
    archetype: 'money',
    element: 'pengukuran',
    unitTitle: 'Aritmetika Sosial Sederhana',
    title: 'Menghitung Total dan Kembalian Belanja',
    summary: 'Menghitung total belanja beberapa barang dan kembalian dengan nominal lebih besar.',
    learningObjective: 'Siswa dapat menghitung total belanja dan kembalian pada transaksi sehari-hari.',
    params: {
      paidWith: 50000,
      prices: [
        { item: 'buku tulis', price: 8500 },
        { item: 'pulpen', price: 6000 },
        { item: 'tas', price: 32000 },
        { item: 'kotak pensil', price: 15000 },
      ],
    },
  },
];

export const { lessons: KELAS_5_LESSONS, videos: KELAS_5_VIDEOS } = buildGrade(5, BRIEFS);
